services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: 
      - "sh"
      - "-c"
      - | 
        pip install debugpy && 
        python -m debugpy --listen 0.0.0.0:5678 django_sqlite_manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
      - 5678:5678
    environment:
      - PYTHONUNBUFFERED=1